version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: votre_mot_de_passe_root
      MYSQL_DATABASE: nom_de_votre_base_de_donnees
      MYSQL_USER: votre_utilisateur
      MYSQL_PASSWORD: votre_mot_de_passe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: